project:
  type: website

website:
  title: "Parsa H. Rafsanjani"
  navbar:
    left:
      - href: index.qmd
        text: About
      - publications/index.qmd
      - posts/index.qmd
      - href: https://phrafsanjani.substack.com/
        text: Newsletter
        target: "_blank"
  favicon: assets/favicon_io/favicon.ico

format:
  html:
    theme:
      light:
        - cosmo
        - brand
      dark:
        - cosmo
        - brand
        - theme-dark.scss
    css: styles.css
    toc: true

execute:
  freeze: auto

