---
title: "Post-pandemic Reflections and Worldview Alterations: On Solitude and Connections"
author: "Parsa H. Rafsanjani"
date: "2026-08-04T15:13:00+03:30"
date-format: "MMMM D, YYYY [at] HH:mm"
categories: [Pandemic, Solitude, Social Media, Seneca, Stoicism]
description: "In this post, I write about the worldview and perspectives I developed during the COVID-19 pandemic, and what changed after that. I write about the value of human connections, my thoughts on social media, embracing the fact that we may change in the future, and living in the present while also embracing the past."
---

## Introduction

When [the pandemic](https://en.wikipedia.org/wiki/COVID-19_pandemic) hit,
I felt an urge to contemplate life and change the way I have been going at it so far.
The anxiety, the isolation, the loneliness, ...;
These feelings led me to watch motivational and educational content on YouTube,
and some of the quotes moved me immensely,
to the point that I decided to dive deeper into philosophy, particularly Stoicism.
I started reading [Seneca's letters to Lucilius](https://en.wikisource.org/wiki/Moral_letters_to_Lucilius),
and as a result, I developed a new worldview.

I was suddenly okay with my isolated, stationary life.
I removed most of my social media (and didn't return to these platforms until very recently),
and I limited my connections.
All I did was learn new skills, read, and watch.
The problem was, even after the pandemic was coming to an end,
and everyone was returning to normal life,
I was so disconnected from the world around me that I continued to enjoy my isolated space.
This stationary life and the feeling of disconnection resulted in an episode of worsened mental condition for me.

## Valuing Human Connection

Although it is important to be alone from time to time,
to reflect on oneself,
and to sit with one's own self in order to better understand it,
exceeding in doing so may later cause problems.
[We are known to be social beings](https://omnia.sas.upenn.edu/story/science-being-social),
and although we are different in socializing and enjoying solitude,
we should realize that we may also change,
that we may later feel the need and desire for deeper and more intimate connections,
and that we may regret the connections we couldn't shape in the early stages of our life.

Though I chose to be content with my isolated life during the pandemic,
and although this alleviated the pain caused by the darkness of those times,
I was mistaken to think of it as the right way to live *forever*.
I was wrong to *stay* disconnected,
and be content with the status quo.
While there is possibility to experience new things,
to meet new souls,
to love and befriend or at least fail in doing so and gain insights from such failure,
why choose to be miserable in one's isolated space,
solely working hard towards a better future,
one which the world is not even indebted to us,
and miss out on other aspects of life?

In fact, speaking for myself, **I enjoy working hard**,
but it is equally important to **keep the balance**,
and while we should be content with our life and enjoy it as much as we can,
we should also realize that there may be even more [in our control](https://www.goodreads.com/quotes/687100-some-things-are-in-our-control-and-others-not-things).
Failing to seize today's opportunities results in tomorrow's regrets,
and then we can do nothing but to [accept it as woven in the pattern of our destiny](https://www.goodreads.com/quotes/32990-accept-whatever-comes-to-you-woven-in-the-pattern-of).

## Social Media Connections

After being away from many of these social media platforms,
I can now manage my time with them much better.
While I understand the social problems caused by social media,
I still believe that one way to connect with others passes through them.
I sometimes think of the opportunities and events that I may have lost because of my lack of usage.
Of course, many past acquaintances are reluctant to connect if the only thread remained is the I-follow-you-and-you-follow-me-back one.
But still, in my opinion, the doors that may be opened shall not be overlooked.

I do not intend to defend social media,
and of course, I myself believe the algorithms are responsible for the many ills caused by them.
But why not utilize some of the better social media spaces to say what we think is needed to be said?
Why do many experts choose to remain silent and avoid it altogether while they see the surge in misinformation?
I understand that many academics and experts simply do not have time for doing so [besides other potential reasons](https://www.reddit.com/r/academia/comments/1rj91wh/why_arent_academics_dominating_social_media/).
Nevertheless, I have recently witnessed more activity on Substack,
although it sounds more like a niche space.
But imagine if more experts allocated more of their time to educate individuals outside a formal setting.

## Letting Go of the Past Despite Recording It

Although I still have mixed feelings about this,
I have started to change in the recent weeks.
As a result of my formed perspectives during the pandemic,
I chose not to put too much value on the past.
It was easy and even joyful to remove social media to break bridges with past individuals,
and I also hated to take pictures and record moments to look at them in the future.
I still share [this view](https://en.wikisource.org/wiki/Page%3AAd_Lucilium_epistulae_morales%2C_volume_1.djvu/201) with Seneca that our past selves are dead,
that we are only alive in each moment,
and as that moment passes by,
the person in that moment passes away with it.

Recently, however, I have started to record some of the *present* moments.
I can always remove the photos and videos later,
but I find it a new entertainment to gather and organize some records of these moments,
some of which are new, even though small, experiences.

## Conclusion

While I developed a new worldview after discovering Stoicism during the pandemic,
I over-isolated myself,
and I missed out on many things.
I am now too far from my Stoic studies,
and in general,
I undervalue solo activities these days,
and while I do not abondon them,
I'd rather spend whatever time I have left socializing,
or in other words,
getting out of my comfort zone.
We change as humans, and we should all take that into account.
I might not want something now,
but what guarantee is there that I will remain such?
Nothing is certain,
and the future uncertainties should be factored into our present affairs.
